/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphic.tool.db;

import java.sql.*;
import java.util.*;
import java.io.*;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.json.CDL;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JTree;
import javax.swing.event.TreeExpansionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.json.JSONException;
import java.lang.*;

/**
 *
 * @author guilhermekoller
 */
public class UI extends javax.swing.JFrame {

    Connection connection;

    /**
     * Creates new form UI
     */
    public UI() {
//        connection.setDatabase("dblivros");
//        connection.setUser("koller");
//        connection.setPassword("password");
        initComponents();
        ComboBoxDB.addItem("MySQL");
        ComboBoxDB.addItem("PostgreSQL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        ScrollTreePanel = new javax.swing.JScrollPane();
        LimitRowsTextField = new javax.swing.JTree();
        MainPanel = new javax.swing.JTabbedPane();
        QueriesPannel = new javax.swing.JPanel();
        TableScrollPanel = new javax.swing.JScrollPane();
        ResultTable = new javax.swing.JTable();
        ExecuteButton = new javax.swing.JButton();
        ExportJSONButton = new javax.swing.JButton();
        ExportCVSButton = new javax.swing.JButton();
        TextAreaScrollPanel = new javax.swing.JScrollPane();
        QueriesTextArea = new javax.swing.JTextArea();
        MaxRowsTextField = new javax.swing.JTextField();
        Labelrow = new javax.swing.JLabel();
        CheckBoxLimit = new javax.swing.JCheckBox();
        SaveDatabaseButton = new javax.swing.JButton();
        DatabaseTextField = new javax.swing.JTextField();
        UserTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        ComboBoxDB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LeftPanel.setBackground(new java.awt.Color(230, 235, 230));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Connections");
        LimitRowsTextField.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        ScrollTreePanel.setViewportView(LimitRowsTextField);

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollTreePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollTreePanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        ResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableScrollPanel.setViewportView(ResultTable);

        ExecuteButton.setText("Execute");
        ExecuteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteButtonActionPerformed(evt);
            }
        });

        ExportJSONButton.setText("Export JSON");
        ExportJSONButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportJSONButtonActionPerformed(evt);
            }
        });

        ExportCVSButton.setText("Export CSV");
        ExportCVSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportCVSButtonActionPerformed(evt);
            }
        });

        QueriesTextArea.setColumns(20);
        QueriesTextArea.setRows(5);
        TextAreaScrollPanel.setViewportView(QueriesTextArea);

        MaxRowsTextField.setText("1000");

        Labelrow.setText("Limit Rows");

        CheckBoxLimit.setSelected(true);
        CheckBoxLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxLimitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QueriesPannelLayout = new javax.swing.GroupLayout(QueriesPannel);
        QueriesPannel.setLayout(QueriesPannelLayout);
        QueriesPannelLayout.setHorizontalGroup(
            QueriesPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QueriesPannelLayout.createSequentialGroup()
                .addGroup(QueriesPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextAreaScrollPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TableScrollPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addGroup(QueriesPannelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Labelrow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxLimit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MaxRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExportCVSButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExportJSONButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExecuteButton)))
                .addContainerGap())
        );
        QueriesPannelLayout.setVerticalGroup(
            QueriesPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QueriesPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextAreaScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QueriesPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxLimit)
                    .addComponent(Labelrow)
                    .addGroup(QueriesPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ExecuteButton)
                        .addComponent(ExportJSONButton)
                        .addComponent(ExportCVSButton)
                        .addComponent(MaxRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        MainPanel.addTab("Queries", QueriesPannel);

        SaveDatabaseButton.setText("Save");
        SaveDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDatabaseButtonActionPerformed(evt);
            }
        });

        DatabaseTextField.setText("Database");

        UserTextField.setText("User");
        UserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setText("Password");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DatabaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxDB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveDatabaseButton)
                    .addComponent(DatabaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel))
        );

        MainPanel.getAccessibleContext().setAccessibleName("New Connection");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExportJSONButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportJSONButtonActionPerformed
        exportCSV();
        try {
            InputStream is = new FileInputStream("/home/guilhermekoller/Documents/Repos/graphic-tool-db/graphic-tool-db/out.csv");
            String csv = new BufferedReader(new InputStreamReader(Objects.requireNonNull(is), StandardCharsets.UTF_8)).lines().collect(Collectors.joining("\n"));
            // Convert csv text to JSON string, and save it 
            // to a data.json file.
            String json = CDL.toJSONArray(csv).toString(2);
            Files.write(Path.of("/home/guilhermekoller/Documents/Repos/graphic-tool-db/graphic-tool-db/out.json"), json.getBytes());
        } catch (IOException e) {
            System.out.println(e);
        } catch (JSONException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ExportJSONButtonActionPerformed

    private void ExecuteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteButtonActionPerformed
        String query = QueriesTextArea.getText();
        String database = DatabaseTextField.getText();
        String user = UserTextField.getText();
        String password = PasswordTextField.getText();
        String DB = (String) ComboBoxDB.getSelectedItem();
        System.out.println(DB);
        int rows = myStringToInteger(MaxRowsTextField.getText());

        try {
            java.sql.Connection conn;

            if ("MySQL".equals(DB)) {
                conn = DriverManager.getConnection("jdbc:mysql://localhost/" + database, user, password);
            } else {
                conn = DriverManager.getConnection("jdbc:postgresql://localhost/" + database, user, password);
            }

            Statement stmt;
            stmt = conn.createStatement();

            if (CheckBoxLimit.isSelected()) {
                stmt.setMaxRows(rows);
            }

            ResultSet rs;
            rs = stmt.executeQuery(query);
            ResultTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_ExecuteButtonActionPerformed

    private void UserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void ExportCVSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportCVSButtonActionPerformed
        exportCSV();
    }//GEN-LAST:event_ExportCVSButtonActionPerformed

    private void SaveDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDatabaseButtonActionPerformed
        String database = DatabaseTextField.getText();
        String user = UserTextField.getText();
        String password = PasswordTextField.getText();
        String DB = (String) ComboBoxDB.getSelectedItem();
        System.out.println(DB);

        DefaultTreeModel model = (DefaultTreeModel) LimitRowsTextField.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        model.insertNodeInto(new DefaultMutableTreeNode(database), root, root.getChildCount());

        DefaultTreeModel child = (DefaultTreeModel) LimitRowsTextField.getModel();
        DefaultMutableTreeNode root2 = (DefaultMutableTreeNode) child.getRoot();
        child.insertNodeInto(new DefaultMutableTreeNode("teste"), root2, root2.getChildCount());

        try {
            java.sql.Connection conn;

            if ("MySQL".equals(DB)) {
                conn = DriverManager.getConnection("jdbc:mysql://localhost/" + database, user, password);
            } else {
                conn = DriverManager.getConnection("jdbc:postgresql://localhost/" + database, user, password);
            }

            Statement stmt;
            stmt = conn.createStatement();

            ResultSet rs;
            rs = stmt.executeQuery("show tables");
            
            while(rs.next()){
                ResultSet tablesRs;
                Statement stmtAux = conn.createStatement();
                tablesRs = stmtAux.executeQuery("show columns from " + rs.getString(1));
                while(tablesRs.next()){
                    if("PRI".equals(tablesRs.getString(4))){
                        System.out.println(tablesRs.getString(1) + " PK");
                    }else if("MUL".equals(tablesRs.getString(4))){
                        System.out.println(tablesRs.getString(1) + " FK");
                    }else{
                        System.out.println(tablesRs.getString(1));
                    }

                }
                System.out.println("----------");
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_SaveDatabaseButtonActionPerformed

    private void CheckBoxLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxLimitActionPerformed

    private void exportCSV() {
        try {
            TableModel model = ResultTable.getModel();
            FileWriter csv;
            csv = new FileWriter(new File("/home/guilhermekoller/Documents/Repos/graphic-tool-db/graphic-tool-db/out.csv"));

            for (int i = 0; i < model.getColumnCount(); i++) {
                csv.write(model.getColumnName(i) + ", ");
            }

            csv.write("\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    csv.write(model.getValueAt(i, j).toString() + ",");
                }
                csv.write("\n");
            }

            csv.close();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    public static int myStringToInteger(String str) {
        int answer = 0, factor = 1;
        for (int i = str.length() - 1; i >= 0; i--) {
            answer += (str.charAt(i) - '0') * factor;
            factor *= 10;
        }
        return answer;
    }

    public void run() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxLimit;
    private javax.swing.JComboBox<String> ComboBoxDB;
    private javax.swing.JTextField DatabaseTextField;
    private javax.swing.JButton ExecuteButton;
    private javax.swing.JButton ExportCVSButton;
    private javax.swing.JButton ExportJSONButton;
    private javax.swing.JLabel Labelrow;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JTree LimitRowsTextField;
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JTextField MaxRowsTextField;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JPanel QueriesPannel;
    private javax.swing.JTextArea QueriesTextArea;
    private javax.swing.JTable ResultTable;
    private javax.swing.JButton SaveDatabaseButton;
    private javax.swing.JScrollPane ScrollTreePanel;
    private javax.swing.JScrollPane TableScrollPanel;
    private javax.swing.JScrollPane TextAreaScrollPanel;
    private javax.swing.JTextField UserTextField;
    // End of variables declaration//GEN-END:variables
}
